### ISSUE TITLE
 working with bootstrap_package v 13.0.1 ?

### ISSUE THREAD

**Issue by edley07** [baschte/content-animations#14]
Hi,
is it possible to use the content animations with the bootstrap_package v 13.0.1?

**Comment by baschte** [comment]
Hey @edley07,
until now the Bootstrap Package 13 isn't supported cause it changed some frame stuff in it. 
I'm working on my extension to support TYPO3 v12 and Bootstrap Package v13 but i can't say when it will be released.

**Comment by edley07** [comment]
Hi Basti,
thanks for the quick info!
Regards André
