### ISSUE TITLE
Animations no longer work with newer versions of t3sbootstrap

### ISSUE THREAD

**Issue by pmarkus84** [baschte/content-animations#15]
Hello,

the extension doesn´t work with t3sbootstrap (at version 5.1.21). With version 5.1.6 the extension works. Have you an idea, what´s the problem ?

![image](https://user-images.githubusercontent.com/29916438/224069238-004c736a-21ea-4013-8de8-cccd2012d1f3.png)

Thanks in advance.

BR
Markus

**Comment by baschte** [comment]
Hey @pmarkus84,
content_animations doesn't support t3sbootstrap and i personally doesn't know it. Maybe the default Layout for this Elements are overwritten from t3sbootstrap and thats why it's not working. But im not sure right now.

Hope you can get it to work.
regards
