### ISSUE TITLE
Syntax Error in AnimationPreviewField.php

### ISSUE THREAD

**Issue by paul-keller** [baschte/content-animations#18]
I just had a problem in a project because of a parse error: 
syntax error, unexpected ')' in content_animations/Classes/Form/Elements/AnimationPreviewField.php on line 220
After removing the comma on line 219 it works for me.

Im using Version 2.4.1 in a TYPO3 10.4.37 installation. But it is running on an old server with PHP 7.2.

**Comment by baschte** [comment]
Hey @paul-keller,
thanks for the hint. I'll check this issue later this day.

**Comment by baschte** [comment]
Hey @paul-keller,
can you try to use the dev-master in your project to test if everything works? Then i'll make a release.

**Comment by paul-keller** [comment]
Thanks @baschte
dev-master is working fine for me

**Comment by baschte** [comment]
Thanks for your feedback @paul-keller.
New version 2.4.2 is out now! 🥳
