### ISSUE TITLE
Can't find those "advanced-animation-settings" as described

### ISSUE THREAD

**Issue by LRWphil** [baschte/content-animations#20]
Hi Sebastin,

Thank you for this cool Extension!

i can't find those **advanced-animation-settings** as described in 

https://github.com/baschte/content-animations/blob/master/Documentation/Administrator/Index.rst#advanced-animation-settings 

#advanced-animation-settings

Thx

**Comment by baschte** [comment]
Hey @LRWphil,
checkout the extensions settings in TYPO3 backend maintanance area and activate the advanced animation settings. They are disabled by default.

Greetings

**Comment by LRWphil** [comment]
Dear @baschte,
Thank you! I Finally found it! Sorry!
Best regards, @LRWphil

Mit freundlichen Grüßen

Philip Warneke
***@***.***

LRW Medien
Inhaber: Philip Warneke e.K.
Am Galgenberg 20
33034 Brakel

Telefon: +49 (0)5271 - 69381 00
Telefax: +49 (0)5271 - 69381 04

E-Mail: ***@***.***
Web: www.lrw-medien.de

Registergericht: Amtsgericht Paderborn
Registernummer: HRA 6310

Zuständiges Finanzamt: Höxter
Steuernummer: 326/5201/1663
USt.-Id-Nr.: DE-316256354

Datenschutzinformationen
Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z. B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. Details entnehmen Sie unserer Datenschutzerklärung (https://www.lrw-medien.de/datenschutz/).
Nachricht von Sebastian Richter ***@***.***> am 15. Nov. 2023, 17:57 +0100:
