### ISSUE TITLE
Feature: Show selected value of the animation from the standard language in translated content elements

### ISSUE THREAD

**Issue by zenoussi** [baschte/content-animations#22]
- TYPO3 12.4.8
- PHP 8.1.13
- container 2.3.1
- content_defender 3.4.1

<img width="861" alt="Bildschirmfoto 2023-11-22 um 13 53 20" src="https://github.com/baschte/content-animations/assets/4442136/9a045de8-855c-4be9-bec0-781acfc03dab">

**Comment by baschte** [comment]
Hey @zenoussi,
translated value is showing now in newest version of content-animations.

Have fun!
