### ISSUE TITLE
Remove Items from labe animations in the Backend with tsconfig 

### ISSUE THREAD

**Issue by CMS-Internetsolutions** [baschte/content-animations#24]
## Default values for EXT:content_animations from my user tsconfig file
#working
TCAdefaults.tt_content.tx_content_animations_animation = fade-in

#not working
TCAdefaults.tt_content.tx_content_animations_animation.removeItems = flip-up,flip-down,flip-left,flip-right

Hello, what am I missing or what am I doing wrong?
Many thanks for a tip. 
Cool Extension it works with the new Contentblocks!!!
thx
Eric

**Comment by baschte** [comment]
Hey @CMS-Internetsolutions 
you have to use „TCEFORM.tt_content…“ instead of „TCADefaults.tt_content…“ if u want to remove or keepItems within the Animations select.

best regards

**Comment by CMS-Internetsolutions** [comment]
Thank you for your fast help!!
Best regards
Eric

**Comment by baschte** [comment]
@CMS-Internetsolutions 
you're welcome!
