### ISSUE TITLE
Compatible with content blocks?

### ISSUE THREAD

**Issue by criwe** [baschte/content-animations#27]
Hi!

I´ve tried to get content animations running with a content blocks element.
I´ve just added

`{f:if(condition: animationSettings, then: '{animationSettings -> f:format.raw()}')} `

to my content block element template, but no output.
Did I miss something?

TYPO3 12.4.12
Content Animations 2.4.2
Content Blocks 0.7.10

Thanks!
Many greetings,
Christoph

**Comment by baschte** [comment]
Hey @criwe 
maybe you have to set the needed DataProcessor settings to your Content Element Typoscript Setup. I didn't work with content blocks right now but im very sure that it's running fine if any ts include and settings are provided to your content block elements.

greetings
Basti

**Comment by criwe** [comment]
Hi @baschte,

thanks for the message.

I have found out that i can access the needed values via  {data._raw.tx_content_animations_animation}, {data._raw.tx_content_animations_duration} etc. and build a simple inline notation in the content blocks elements:

`{f:if(condition:'{data._raw.tx_content_animations_animation}',then:' data-aos="{data._raw.tx_content_animations_animation}" {f:if(condition:\'{data._raw.tx_content_animations_duration}\',then:\' data-aos-duration="{data._raw.tx_content_animations_duration}"\',else:\' data-aos-duration="800"\')}
    {f:if(condition:\'{data._raw.tx_content_animations_delay}\',then:\' data-aos-delay="{data._raw.tx_content_animations_delay}"\',else:\' data-aos-delay="0" \')} data-aos-once="true" data-aos-easing="ease" data-aos-mirror="false"',else:'')} `

Maybe not the best solution, but enough for my usecase.

All backend stuff (i.e. animation footer label) works out of the box.

Greetings,
Christoph

**Comment by baschte** [comment]
Hey @criwe, thank you for your Solution! Maybe i‘ll try it out and Check how you can use it together.

greetings!
