### ISSUE TITLE
Use with Content Blocks

### ISSUE THREAD

**Issue by stephangrass** [baschte/content-animations#29]
Hi,
how can I user ContentAnimations with Content Blocks? It seems, that the animationSettings are not set in the fluid-templates.
I use Fluid-Styled-Content with Content-Blocks:

```

lib.contentBlock {
    partialRootPaths.0 < lib.contentElement.partialRootPaths.0
    layoutRootPaths.0 < lib.contentElement.layoutRootPaths.0

    templateRootPaths.200 = EXT:ext/Resources/Private/Extensions/fluid_styled_content/Resources/Private/Templates/
    partialRootPaths.200 = EXT:ext/Resources/Private/Extensions/fluid_styled_content/Resources/Private/Partials/
    layoutRootPaths.200 = EXT:ext/Resources/Private/Extensions/fluid_styled_content/Resources/Private/Layouts/

    settings < lib.contentElement.settings
}

```

In my layout I set 

`{f:if(condition: animationSettings, then: '{animationSettings -> f:format.raw()}')}`

but animationSettings ist empty anywhere ...

Thanks for a hint.

**Comment by baschte** [comment]
Hi @stephangrass 
i think you have to add the needed Dataprocessor as well to your typoscript to get content_animations working with content blocks.

```
    # stuff for content-animations
    variables {
        aos-easing < plugin.tx_content_animations.variables.aos-easing
        aos-once < plugin.tx_content_animations.variables.aos-once
        aos-mirror < plugin.tx_content_animations.variables.aos-mirror
    }
    dataProcessing.78911002 < plugin.tx_content_animations.dataProcessing.78911002```

hope it helps.

**Comment by stephangrass** [comment]
Hi, thanks!

but when I try to use your code, I will get the error:

`
Baschte\ContentAnimations\DataProcessing\AnimationSettingsProcessor::prefixAndSetValuesToAnimationOptions(): Argument #1 ($dataObj) must be of type array, TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlockData given, called in /var/www/html/vendor/baschte/content-animations/Classes/DataProcessing/AnimationSettingsProcessor.php on line 90
`

Any idea?
