### ISSUE TITLE
Feature Request: Support of extension bootstrap-package

### ISSUE THREAD

**Issue by McKoy61** [baschte/content-animations#3]
At the moment, your very nice extensions breaks the frontend-output of pages based on the bootstrap-package (f.e. bootstrap-carousel ist not shown, grid-structure is destroyed). Is there a way to adapt it?

**Comment by baschte** [comment]
Hi @McKoy61 yes of course it is. As in the documentation shown you have to add a **custom Default.html** fluid layout to support the bootstrap package. 

Put this line before the ">" of the div in line 22 and the bootstrap package should work fine.
https://docs.typo3.org/typo3cms/extensions/content_animations/Developer/Index.html#extending

`{f:if(condition: data.tx_content_animations_animation, then: ' data-aos="{data.tx_content_animations_animation}" data-aos-duration="{data.tx_content_animations_duration}" data-aos-delay="{data.tx_content_animations_delay}" data-aos-once="{f:if(condition: aos-once, then: \'true\', else: \'false\')}" data-aos-easing="{aos-easing}" data-aos-mirror="{f:if(condition: aos-mirror, then: \'true\', else: \'false\')}"')}`

https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Layouts/ContentElements/Default.html#L22

The you have to update the layoutRootPaths for fluid to get your Default.html Layout first and everything is fine.

Maybe i try to support it out of the box to guarantee a nice experience 🤔

**Comment by baschte** [comment]
@McKoy61 
Version 1.1.0 of content_animations is released. Now with full Bootstrap Package v10, v9 and v8 support. Also Fluid Styled Content and Higher Education Package v9 are supported.

To get it working only reinclude the right static typoscript of content_animations to your project.
Have fun 🎉

**Comment by McKoy61** [comment]
> @McKoy61
> Version 1.1.0 of content_animations is released. Now with full Bootstrap Package v10, v9 and v8 support. Also Fluid Styled Content and Higher Education Package v9 are supported.
> 
> To get it working just include the right static typoscript of content_animations to your project.
> Have fun 🎉
@baschte 
Hi Basti, thanks for your quick reaction and support, thats great!
Sorry for reopening, but for me it seems not to work. Frontend-Output of bootstrap-package is ok now, but the animation-tab is not shown while editing content elements.
Typo3 9.5.5
bootstrap_package 10.0.6  
bootstrap 4 (SCSS)
php 7.3
Thanks!

**Comment by baschte** [comment]
@McKoy61 
Mhh ok that's weird 🤔 Tested it yesterday on TYPO3 9.5.5 LTS with Bootstrap Package v10 and CMS Introduction Package. Maybe i'll check that this Weekend and try to get this problem. So if you edit an CE it doesn't show the animation tab, right? Have you tried to deinstall and install the extension via extension manager and clear all caches?

If you want you can contact me in TYPO3 slack. That would be easyer for me. My Username is @baschte.

Best regards!

**Comment by edekowalski** [comment]
I had the same Effect but after reinstall and install the extension via extension manager and clear all caches and reload the Browser. It works again. 

For your Information.

**Comment by baschte** [comment]
Oh ok so maybe it‘s wrong in the cache or something like that. I changed a few things now. Can you pls write your Project environment @edekowalski? Thx for your Info

**Comment by edekowalski** [comment]
TYPO3 8.7.24
PHP 7.2
Fluid Styled Content

Best Regards
