### ISSUE TITLE
[FEATURE] Add more AOS-Option in CE

### ISSUE THREAD

**Issue by stephangrass** [baschte/content-animations#5]
Hi,

it will be fine, if more aos-options are available for set up in ce's.
For example data-aos-offset, data-aos-easing, data-aos-once or data-aos-anchor-placement.

Stephan

**Comment by baschte** [comment]
Hi @stephangrass ,

yeah that could be nice if your editors or customers are able to set these options right 😅 Otherwise it could overstrain them. I think i'll implement these extended options for people who need them as soon as possible.

thanks for your feedback!

**Comment by baschte** [comment]
@stephangrass 
New version [2.0.0](https://github.com/baschte/content-animations/releases/tag/2.0.0) of content animations is out with advanced settings for animations. Have fun! 😁👍🏻
