### ISSUE TITLE
[TASK] Add support for TYPO3 11.4

### ISSUE THREAD

**Issue by glucka** [baschte/content-animations#7]

**Comment by baschte** [comment]
Hey @glucka 
new version 2.2.0 of content_animations is released with full TYPO3 v11.4 and Bootstrap Package v12 support.

have fun with animating your content!

**Comment by glucka** [comment]
Thank You!!!!!!!!!!!!!!!!

**Comment by baschte** [comment]
You’re welcome! 😁
