### ISSUE TITLE
Content-animations stopped working after update to TYPO3 11.5.1

### ISSUE THREAD

**Issue by ivanbilj** [baschte/content-animations#8]
After updating from v11.5.0 to v11.5.1 I get following error: Uncaught ReferenceError: AOS is not defined.
Last lines in view-source:

/*<![CDATA[*/
/*TS_inlineFooter*/
AOS.init();

/*]]>*/
</script>

</body>
</html>

**Comment by baschte** [comment]
Hey @ivanbilj,
that's very strange cause i didn't do anything on the JS implementation of the extension. Maybe the fault is anywhere else in your project?

best regards

**Comment by baschte** [comment]
Maybe you can send me a gist with your composer.json and i‘ll check out whats the problem right now.
